module.exports = function (data) {
  let familyMemberRows = [];

  familyMemberRows.push([
    { text: "Family Members" },
    { text: "Occupation1" },
    { text: "Employement Type" },
    { text: "Frequency of Income(D/W/M)" },
    { text: "Income Per Month" },
    { text: "Occupatio" },
    { text: "Employement Type" },
    { text: "Frequency of Income" },
    { text: "Income per month" },
    { text: "Total" },
  ]);

  let microfinanceLoanTable = [];

  microfinanceLoanTable.push(
    [
      { text: "THE FEDERAL BANK LTD", alignment: "center", colSpan: 10 },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
    [
      {
        text: "Microfinance Loan - House Hold Income Assessment Sheet for JLG Members",
        alignment: "center",
        colSpan: 10,
      },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
    [
      { text: "BC Name", colSpan: 1 },
      { text: "", colSpan: 1 },
      { text: "BC Branch" },
      { text: "", colSpan: 1 },
      { text: "Date" },
      { text: "", colSpan: 1 },
      { text: "Center" },
      { text: "", colSpan: 1 },
      { text: "Group" },
      { text: "", colSpan: 1 },
    ],
    [{ text: "Customer Name", colSpan: 1 }, {}, {}, {}, {}, {}, {}, {}, {}, {}],
    [
      { text: "PART A - INCOME", alignment: "center", colSpan: 10 },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],

    //PART - A INCOME
    [
      { text: "Family Members" },
      { text: "Occupation1" },
      { text: "Employement Type" },
      { text: "Frequency of Income(D/W/M)" },
      { text: "Income Per Month" },
      { text: "Occupatio" },
      { text: "Employement Type" },
      { text: "Frequency of Income" },
      { text: "Income per month" },
      { text: "Total" },
    ],
    [{ text: "Member" }, {}, {}, {}, {}, {}, {}, {}, {}, {}],
    [{ text: "Spouse" }, {}, {}, {}, {}, {}, {}, {}, {}, {}],
    [{ text: "Unmarried Son" }, {}, {}, {}, {}, {}, {}, {}, {}, {}],
    [{ text: "Unmarried Daughter" }, {}, {}, {}, {}, {}, {}, {}, {}, {}],
    [
      { text: "Total household income(A)", colSpan: 2 },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],

    // PART - B EXPENSES
    [
      { text: "PART B - EXPENSES", alignment: "center", colSpan: 10 },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
    [
      { text: "Loan obligations", colSpan: 6, alignment: "center" },
      {},
      {},
      {},
      {},
      {},
      { text: "Expenses-Regular", colSpan: 2 },
      {},
      { text: "Expenses-Regular", colSpan: 2 },
      {},
    ],
    [
      { text: "Loan Type", colSpan: 2 },
      {},
      { text: "Loan Amount" },
      { text: "EMI" },
      { text: "Remaining Tenure" },
      { text: "Expense Type" },
      { text: "Amount per month" },
      { text: "Expense Type" },
      { text: "Amount per month", colSpan: 2 },
      {},
    ],
    [
      { text: "MFI Loan", colSpan: 2 },
      {},
      {},
      {},
      {},
      { text: "Rent" },
      {},
      { text: "Medical" },
      {},
      {},
    ],
    [
      { text: "Vehicle Loan", colSpan: 2 },
      {},
      {},
      {},
      {},
      { text: "Food" },
      {},
      { text: "Others" },
      {},
      {},
    ],
    [
      { text: "Mortgage Loan", colSpan: 2 },
      {},
      {},
      {},
      {},
      { text: "Clothing" },
      {},
      {},
      {},
      {},
    ],
    [
      { text: "Consumer durable loan", colSpan: 2 },
      {},
      {},
      {},
      {},
      { text: "Education" },
      {},
      {},
      {},
      {},
    ],
    [
      { text: "Others", colSpan: 2 },
      {},
      {},
      {},
      {},
      { text: "Others" },
      {},
      {},
      {},
      {},
    ],
    [
      { text: "Total", colSpan: 2 },
      {},
      {},
      {},
      {},
      { text: "Total" },
      {},
      {},
      {},
      {},
    ],
    [
      { text: "Eligibilty Assesment", alignment: "center", colSpan: 10 },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
    [
      { text: "EMI of the proposed loan", colSpan: 2 },
      {},
      { text: "EMI of the proposed loan", colSpan: 2 },
      {},
      {},
      {
        text: "Total monthly obligations(including proposed loan)(B)",
        colSpan: 3,
      },
      {},
      {},
      {},
      {},
    ],
    [
      { text: "Debt Burden Ratio" },
      { text: "(B)/(A)*100" },
      { text: "", colSpan: 3 },
      {},
      {},
      { text: "Signature of member", colSpan: 2 },
      {},
      { text: "", colSpan: 3 },
      {},
      {},
    ],
    [
      { text: "*Member is eligible, if DBR is less than 50%", colSpan: 3 },
      {},
      {},
      {},
      {},
      { text: "Signature of Field Officer", colSpan: 2 },
      {},
      { text: "", colSpan: 3 },
      {},
      {},
    ]
  );

  return [
    {
      table: {
        widths: [
          "10%",
          "10%",
          "10%",
          "10%",
          "10%",
          "10%",
          "10%",
          "10%",
          "10%",
          "10%",
        ],
        body: microfinanceLoanTable,
      },
      style: "tableLeftAlignedWithSmallFont",
      bold: true,
      pageBreak: "after",
    },
  ];
};
